# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a1e5c530861a386509fe6c2c3056c383"
name = "Nova Post Courier"
handle = "nova-post-courier"
application_url = "https://courier.nova-post-shopify.stg2.stfalcon.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "novapost-staging.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_shipping,write_customers,write_orders,write_products,write_shipping"

[auth]
redirect_urls = [
  "https://courier.nova-post-shopify.stg2.stfalcon.com/auth/callback",
  "https://courier.nova-post-shopify.stg2.stfalcon.com/auth/shopify/callback",
  "https://courier.nova-post-shopify.stg2.stfalcon.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://courier.nova-post-shopify.stg2.stfalcon.com/webhooks"

[pos]
embedded = false
